# Generated by Django 5.1.7 on 2025-03-30 04:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfer", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="encrptedfile",
            old_name="uploaded_at",
            new_name="uploaded_date",
        ),
        migrations.AddField(
            model_name="encrptedfile",
            name="file_size",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="encrptedfile",
            name="original_filename",
            field=models.FileField(
                default=django.utils.timezone.now, max_length=255, upload_to=""
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="FileLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("download_time", models.IntegerField(default=0)),
                (
                    "download_final_datetime",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "encrptedFile",
                    models.ForeignKey(
                        db_column="file_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="transfer.encrptedfile",
                    ),
                ),
            ],
        ),
    ]
