# Generated by Django 5.1.7 on 2025-03-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_rename_uploaded_at_encrptedfile_uploaded_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encrptedfile',
            name='original_filename',
            field=models.CharField(max_length=100),
        ),
    ]
