# Generated by Django 5.2 on 2025-04-18 19:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_alter_encrptedfile_original_filename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requester_email', models.EmailField(max_length=254)),
                ('requester_name', models.CharField(max_length=100)),
                ('request_message', models.TextField(blank=True)),
                ('public_key', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_fulfilled', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='encrptedfile',
            name='auth_tag',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encrptedfile',
            name='encrypted_aes_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encrptedfile',
            name='encryption_algorithm',
            field=models.CharField(blank=True, default='AES-256-GCM', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='encrptedfile',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='encrptedfile',
            name='iv',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encrptedfile',
            name='recipient_key_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encrptedfile',
            name='recipient_public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encrptedfile',
            name='sender_key_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filelog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filelog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='KeyPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_key', models.TextField()),
                ('private_key_salt', models.BinaryField(blank=True, null=True)),
                ('encrypted_private_key', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
