# Generated by Django 5.2 on 2025-04-18 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0004_filerequest_encrptedfile_auth_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encrptedfile',
            name='auth_tag',
        ),
        migrations.RemoveField(
            model_name='encrptedfile',
            name='recipient_key_id',
        ),
        migrations.RemoveField(
            model_name='encrptedfile',
            name='sender_key_id',
        ),
    ]
